# -*- coding: utf-8 -*-
"""Indice_Remissivo_AVL (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQ0csc2gLPi2mcVKh-8MnPWoicIrUJ2v

<a href="https://colab.research.google.com/github/Silvanaluz/Tarefas-de-Estrutura-de-dados-2/blob/main/Indice_Remissivo_AVL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Índice Remissivo utilizando Árvore AVL
Disciplina: Estrutura de Dados 2

Aluna: Silvana Luz de Sousa

Aliuna: Danyella Alves

# Índice Remissivo com Árvore AVL

## 1️⃣ Upload do arquivo .txt
"""

from google.colab import files
files.upload()

"""## 2️⃣ Leitura do arquivo"""

with open("proverbiosB.txt", "r", encoding="utf-8", errors="ignore") as arquivo:
    texto = arquivo.read()

"""## 3️⃣ Estrutura do Nó"""

import re
import time

class No:
    def __init__(self, palavra, linha):
        self.palavra = palavra
        self.linhas = {linha}
        self.esquerda = None
        self.direita = None
        self.altura = 1

"""## 4️⃣ Implementação da Árvore AVL"""

class AVL:
    def __init__(self):
        self.raiz = None
        self.rotacoes = 0
        self.total_palavras = 0
        self.descartadas = 0

    def altura(self, no):
        return no.altura if no else 0

    def fator_balanceamento(self, no):
        return self.altura(no.esquerda) - self.altura(no.direita)

    def rotacao_direita(self, y):
        self.rotacoes += 1
        x = y.esquerda
        t2 = x.direita
        x.direita = y
        y.esquerda = t2
        y.altura = 1 + max(self.altura(y.esquerda), self.altura(y.direita))
        x.altura = 1 + max(self.altura(x.esquerda), self.altura(x.direita))
        return x

    def rotacao_esquerda(self, x):
        self.rotacoes += 1
        y = x.direita
        t2 = y.esquerda
        y.esquerda = x
        x.direita = t2
        x.altura = 1 + max(self.altura(x.esquerda), self.altura(x.direita))
        y.altura = 1 + max(self.altura(y.esquerda), self.altura(y.direita))
        return y

    def inserir(self, no, palavra, linha):
        self.total_palavras += 1
        if not no:
            return No(palavra, linha)

        if palavra < no.palavra:
            no.esquerda = self.inserir(no.esquerda, palavra, linha)
        elif palavra > no.palavra:
            no.direita = self.inserir(no.direita, palavra, linha)
        else:
            if linha in no.linhas:
                self.descartadas += 1
            else:
                no.linhas.add(linha)
            return no

        no.altura = 1 + max(self.altura(no.esquerda), self.altura(no.direita))
        fb = self.fator_balanceamento(no)

        if fb > 1 and palavra < no.esquerda.palavra:
            return self.rotacao_direita(no)
        if fb < -1 and palavra > no.direita.palavra:
            return self.rotacao_esquerda(no)
        if fb > 1 and palavra > no.esquerda.palavra:
            no.esquerda = self.rotacao_esquerda(no.esquerda)
            return self.rotacao_direita(no)
        if fb < -1 and palavra < no.direita.palavra:
            no.direita = self.rotacao_direita(no.direita)
            return self.rotacao_esquerda(no)

        return no

    def remover(self, no, palavra, linha):
        if no is None:
            return None

        if palavra < no.palavra:
            no.esquerda = self.remover(no.esquerda, palavra, linha)
        elif palavra > no.palavra:
            no.direita = self.remover(no.direita, palavra, linha)
        else:
            if linha in no.linhas:
                no.linhas.remove(linha)

            if len(no.linhas) > 0:
                return no

            if no.esquerda is None:
                return no.direita
            elif no.direita is None:
                return no.esquerda

            sucessor = self.minimo(no.direita)
            no.palavra = sucessor.palavra
            no.linhas = sucessor.linhas
            no.direita = self.remover(no.direita, sucessor.palavra, next(iter(sucessor.linhas)))

        if no is None: return None

        no.altura = 1 + max(self.altura(no.esquerda), self.altura(no.direita))
        fb = self.fator_balanceamento(no)

        if fb > 1 and self.fator_balanceamento(no.esquerda) >= 0:
            return self.rotacao_direita(no)
        if fb > 1 and self.fator_balanceamento(no.esquerda) < 0:
            no.esquerda = self.rotacao_esquerda(no.esquerda)
            return self.rotacao_direita(no)
        if fb < -1 and self.fator_balanceamento(no.direita) <= 0:
            return self.rotacao_esquerda(no)
        if fb < -1 and self.fator_balanceamento(no.direita) > 0:
            no.direita = self.rotacao_direita(no.direita)
            return self.rotacao_esquerda(no)

        return no

    def minimo(self, no):
        atual = no
        while atual.esquerda is not None:
            atual = atual.esquerda
        return atual

    def buscar(self, no, palavra):
        if no is None or no.palavra == palavra:
            return no
        if palavra < no.palavra:
            return self.buscar(no.esquerda, palavra)
        return self.buscar(no.direita, palavra)

    def contar_nos(self, no):
        if no is None: return 0
        return 1 + self.contar_nos(no.esquerda) + self.contar_nos(no.direita)

    def buscar_com_me(self, palavra):
        no_alvo = self.buscar(self.raiz, palavra)
        if not no_alvo:
            return -1

        esq = self.contar_nos(no_alvo.esquerda)
        dire = self.contar_nos(no_alvo.direita)
        me = esq - dire

        if me == 0:
            return 0
        else:
            print(f"Medidor de Equilíbrio (ME) para '{palavra}': {me}")
            return 1

    def buscar_prefixo(self, prefixo):
        resultado = []
        self._buscar_prefixo_rec(self.raiz, prefixo.lower(), resultado)
        return sorted(resultado)

    def _buscar_prefixo_rec(self, no, prefixo, resultado):
        if no is None: return
        if no.palavra.startswith(prefixo):
            resultado.append(no.palavra)
        if prefixo <= no.palavra:
            self._buscar_prefixo_rec(no.esquerda, prefixo, resultado)
        if prefixo >= no.palavra[:len(prefixo)]:
            self._buscar_prefixo_rec(no.direita, prefixo, resultado)

    def palavra_mais_frequente(self):
        self.mais_frequente = None
        self._percorrer_frequencia(self.raiz)
        return self.mais_frequente

    def _percorrer_frequencia(self, no):
        if no:
            if self.mais_frequente is None or len(no.linhas) > len(self.mais_frequente.linhas):
                self.mais_frequente = no
            self._percorrer_frequencia(no.esquerda)
            self._percorrer_frequencia(no.direita)

    def imprimir_indice_completo(self, tempo_construcao):
        total_distintas = self.contar_nos(self.raiz)

        print("\n" + "="*40)
        print(" ÍNDICE REMISSIVO COMPLETO (ORDEM ALFABÉTICA) ")
        print("="*40)

        self._imprimir_em_ordem(self.raiz)

        print("\n" + "="*40)
        print(" ESTATÍSTICAS FINAIS ")
        print("="*40)
        print(f"Total de palavras processadas: {self.total_palavras}")
        print(f"Total de palavras distintas: {total_distintas}")
        print(f"Total de palavras descartadas: {self.descartadas}")
        print(f"Tempo de construção: {tempo_construcao:.4f} segundos")
        print(f"Total de rotações executadas: {self.rotacoes}")
        print("="*40 + "\n")

    def _imprimir_em_ordem(self, no):
        if no:
            self._imprimir_em_ordem(no.esquerda)
            # Imprime na tela: Palavra: [linha1, linha2]
            print(f"{no.palavra}: {sorted(list(no.linhas))}")
            self._imprimir_em_ordem(no.direita)

# --- Processamento ---

def processar_texto(caminho_arquivo):
    arvore = AVL()
    inicio = time.time()
    try:
        with open(caminho_arquivo, "r", encoding="utf-8") as f:
            for num_linha, linha in enumerate(f, 1):
                palavras = re.findall(r"[a-zA-ZÀ-ÿ]+", linha.lower())
                for p in palavras:
                    arvore.raiz = arvore.inserir(arvore.raiz, p, num_linha)
    except FileNotFoundError:
        print("Erro: Arquivo não encontrado.")
        return None, 0
    fim = time.time()
    return arvore, (fim - inicio)

def main():
    arquivo = "proverbiosB.txt"
    arvore, tempo = processar_texto(arquivo)

    if not arvore: return

    # Teste de Busca com ME
    print("\n--- Teste 1: buscar_com_me ---")
    termo = "sabedoria"
    status = arvore.buscar_com_me(termo)
    if status == -1: print(f"A palavra '{termo}' não foi encontrada.")
    elif status == 0: print(f"A palavra '{termo}' foi encontrada e o ME é zero.")
    else: print(f"A palavra '{termo}' existe (ME impresso acima).")

    # Busca por Prefixo
    prefixo = "alg"
    print(f"\n--- Teste 2: buscar_prefixo ('{prefixo}') ---")
    print(arvore.buscar_prefixo(prefixo))

    # Palavra mais frequente
    freq = arvore.palavra_mais_frequente()
    if freq:
        print(f"\n--- Teste 3: Palavra mais frequente ---")
        print(f"Palavra: '{freq.palavra}' | Aparece em {len(freq.linhas)} linhas.")

    arvore.imprimir_indice_completo(tempo)

if __name__ == "__main__":
    main()

"""Conclusão:

Testes executados: inserção, busca, prefixo, estatísticas e ordenação alfabética.
"""